# Generated by Django 3.2.18 on 2023-03-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar', 'Andaman & Nicobar'), ('Andrapradesh', 'Andrapradesh'), ('Karanataka', 'Karanataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Bihar', 'Bihar'), ('Telangana', 'Telangana'), ('Punjab', 'Punjab'), ('Maharastra', 'Maharastra'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujat'), ('Harayana', 'Harayana'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir '), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fertilizers'), ('FS', 'FlowerSeeds'), ('VS', 'VegetableSeeds'), ('PS', 'Pesticides'), ('PD', 'Petsfood')], max_length=2),
        ),
    ]
